### ISSUE TITLE
The GUID are identical.

### ISSUE THREAD

**Issue by LaurentDardenne** [Jaykul/SxSTest#1]
Hi Joel,
the GUID keys in the manifest are identical.

**Comment by Jaykul** [comment]
Yes, of course they are. You don't change the GUID when you version a module.

**Comment by LaurentDardenne** [comment]
> > Yes, of course they are. You don't change the GUID when you version a module.

Ok.

Here the following reasons why i have changed one GUID   

``` powershell
#Origine
Import-module SxSTest -RequiredVersion 1.0
Import-module SxSTest -RequiredVersion 2.0
get-module -FullyQualifiedName @{ModuleName="SxSTest"; ModuleVersion ='1.0'; GUID='034547e3-5599-4b6b-945e-af3a25a6f66c'}
# 
# ModuleType Version    Name                                ExportedCommands
# ---------- -------    ----                                ----------------
# Script     1.0        SxSTest                             {Get-ModuleVersion, Get-SxSVersion, Invoke-Test}
# Script     2.0        SxSTest                             {Get-ModuleVersion, Get-SxSVersion, Invoke-Test}

get-module sxstest|select Guid,Path

# Guid                                 Path
# ----                                 ----
# 034547e3-5599-4b6b-945e-af3a25a6f66c C:\Program Files\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psm1
# 034547e3-5599-4b6b-945e-af3a25a6f66c C:\Program Files\WindowsPowerShell\Modules\SxSTest\2.0\SxSTest.psm1


#GUID changed
Import-module SxSTest -RequiredVersion 1.0
Import-module SxSTest -RequiredVersion 2.0
get-module -FullyQualifiedName @{ModuleName="SxSTest"; ModuleVersion ='1.0'; GUID='034547e3-5599-4b6b-945e-af3a25a6f66c'}
# ModuleType Version    Name                                ExportedCommands
# ---------- -------    ----                                ----------------
# Script     1.0        SxSTest                             {Get-ModuleVersion, Get-SxSVersion, Invoke-Test}


get-module sxstest|select Guid,Path
# 
# Guid                                 Path
# ----                                 ----
# 034547e3-5599-4b6b-945e-af3a25a6f66c C:\Program Files\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psm1
# 024547e3-5599-4b6b-945e-af3a25a6f66c C:\Program Files\WindowsPowerShell\Modules\SxSTest\2.0\SxSTest.psm1
```

And with this point(https://connect.microsoft.com/PowerShell/Feedback/Details/786022), I understand to why i am confuse with the versionning module under Powershell.

**Comment by Jaykul** [comment]
Get-Module's "FullyQualifiedName" matches the "Version" with "Minimum Version" semantics.

If you do a search with the ModuleVersion = "1.1" you'll see you get only the 2.0 module.

Import-Module with that FullyQualifiedModule will import version 2.0, because it chooses the highest version despite the FullyQualifiedModule.  If you specify -Version 1.0, the same thing happens because "Version" is aliased to "MinimumVersion"

To get 1.0 you have to use -RequiredVersion

It's frustrating to me that PowerShell doesn't understand semantic versioning -- in this situation, where I've bothered to include the fully qualified name, I feel it should require **at least** the major version to match (I'd almost prefer an exact version match).  

However, changing the GUID is pointless. You might as well not have a GUID if you change it with every version, because now there's no way to see continuity -- it looks like a module developed by someone else which got the same name purely by coincidence.

**Comment by LaurentDardenne** [comment]
Thanks Joel.

> "However, changing the GUID is pointless"

I agree.
Here, I adapted to the problem without solving it.

I added a filter :

``` powershell
get-module -FullyQualifiedName @{ModuleName="SxSTest"; ModuleVersion ='1.0'; GUID='034547e3-5599-4b6b-945e-af3a25a6f66c'} 
 |Where {$_.Version -eq '1.0'}
```

Two module with same GUID, only one object.

> "To get 1.0 you have to use -RequiredVersion"

Ok.
But in the following case this is not enough :

1)Copy the 'C:\Program Files\WindowsPowerShell\Modules\SxSTest' directory to the psprofile path : "$($env:psmodulepath -split ';')[0]\SxSTest'

2)Change the GUIDs (for v1 and v2) 
 GUID = '024547e3-5599-4b6b-945e-af3a25a6f66c' 

Now :

``` powershell
get-module sxstest -list|select version,guid,path|fl
# Version : 2.0
# Guid    : 024547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Users\Laurent\Documents\WindowsPowerShell\Modules\SxSTest\2.0\SxSTest.psd1
# 
# Version : 1.0
# Guid    : 024547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Users\Laurent\Documents\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psd1
# 
# Version : 2.0
# Guid    : 034547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Program Files\WindowsPowerShell\Modules\SxSTest\2.0\SxSTest.psd1
# 
# Version : 1.0
# Guid    : 034547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Program Files\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psd1

Import-module SxSTest -RequiredVersion 1.0
get-module sxstest|select version,guid,path|fl
# Version : 1.0
# Guid    : 024547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Users\Laurent\Documents\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psm1 

#First path in $env:PSModulePath
$env:PSModulePath -split';'
# C:\Users\Laurent\Documents\WindowsPowerShell\Modules
# C:\Program Files\WindowsPowerShell\Modules
# C:\Windows\system32\WindowsPowerShell\v1.0\Modules\  
```

Exit, new PS console :

``` powershell
Import-module -FullyQualifiedName @{ModuleName="SxSTest"; ModuleVersion ='1.0'; GUID='034547e3-5599-4b6b-945e-af3a25a6f66c'}
# Version : 2.0
# Guid    : 034547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Program Files\WindowsPowerShell\Modules\SxSTest\2.0\SxSTest.psm1
```

Almost...
Ok same rule about 'FQN':

> "Import-Module with that FullyQualifiedModule will import version 2.0 ..."

Exit, new PS console :

``` powershell
ipmo -Name 'C:\Program Files\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psd1'
get-module sxstest|select version,guid,path|fl
# Version : 1.0
# Guid    : 034547e3-5599-4b6b-945e-af3a25a6f66c
# Path    : C:\Program Files\WindowsPowerShell\Modules\SxSTest\1.0\SxSTest.psm1

#Ouf, enfin !
#Phew, finally done.
```

My goal is to test the class versioning with your two modules.
Next step : How to rehydrate an instance with the correct module version.

**Comment by LaurentDardenne** [comment]
Not yet awakened :-/
This works :

``` powershell
Import-module -FullyQualifiedName @{ModuleName="SxSTest"; RequiredVersion ='1.0'; GUID='034547e3-5599-4b6b-945e-af3a25a6f66c'}
```

**Comment by Jaykul** [comment]
Yeah, they added "RequiredVersion" for both `#requires` and the `FullyQualifiedName` hashtable for `Get-Module` and `Import-Module` in PS5.
